ecommerce_platform/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('order/', include('order.urls', namespace='order')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
) + debug_toolbar_urls()


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header = 'Tea Shop Admin'
admin.site.index_title = 'Tea Shop'

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/update/', views.UpdateCartView.as_view(), name='update_cart_item'),
    path('cart/remove/', views.RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
]

store/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name='store'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category', cache_page(60 * 10)(views.TeaListView.as_view()), name='shop'),
    path('category/<slug:slug>/', cache_page(60 * 10)(views.TeaListView.as_view()), name='category_page'),
    path('search/', views.TeaListView.as_view(), name='search'),
    path('product/<slug:slug>/', views.TeaDetailView.as_view(), name='product_page'),
    path('contact/', views.send_email, name='contact'),
]

templates/partials/categories.html
{% load i18n %}

<h4>{% trans "Categories" %}</h4>
<ul class="list-unstyled tea-categorie">
    {% for category in categories %}
        <li>
            <div class="d-flex justify-content-between tea-name">
                <a href="{% url 'store:category_page' category.slug %}"><i class="fas fa-mug-hot me-2"></i>{{ category.name }}</a>
                <span>({{ category.product_count }})</span>
            </div>
        </li>
    {% endfor %}
</ul>

templates/partials/holiday-products.html
{% load i18n %}

{% for holiday_product in holiday_products %}
    <a href="{% url 'store:product_page' holiday_product.slug %}" class="tea-link">
        <div class="d-flex align-items-center justify-content-start">
            <div class="rounded me-4" style="width: 100px; height: 100px;">
                <img src="{{ holiday_product.image.url }}" class="img-fluid rounded" alt="">
            </div>
            <div>
                <h6 class="mb-2">{{ holiday_product.name }}</h6>
                <div class="d-flex mb-2">
                    {% for i in '12345' %}
                        {% if forloop.counter <= holiday_product.rating %}
                            <i class="fa fa-star text-secondary"></i>
                        {% else %}
                            <i class="fa fa-star"></i>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="d-flex mb-2">
                    <h5 class="fw-bold me-2">$5.00</h5>
                    <h5 class="text-danger text-decoration-line-through">${{ holiday_product.price }}</h5>
                </div>
            </div>
        </div>
    </a>
{% endfor %}

<div class="d-flex justify-content-center my-4">
    <a href="#" class="btn border border-secondary px-4 py-3 rounded-pill text-primary w-100">{% trans "View More" %}</a>
</div>

templates/partials/related-products.html
{% load static %}
{% load i18n %}

<div class="owl-carousel vegetable-carousel justify-content-center">
    {% for product in related_products %}
        <div class="border border-primary rounded position-relative related-product-item">
            <div class="related-product-img">
                <a href="{% url 'store:product_page' product.slug %}" class="tea-link">
                    <img src="{{ product.image.url }}" class="img-fluid w-100 rounded-top" alt="">
                </a>
            </div>
            <div class="text-white bg-primary px-3 py-1 rounded position-absolute" style="top: 10px; right: 10px;">
                {{ product.category.name }}</div>
            <div class="p-4 pb-0 rounded-bottom">
                <a href="{% url 'store:product_page' product.slug %}" class="tea-link">
                    <h4 class="text-truncate">{{ product.name }}</h4>
                </a>
                <form action="{% url 'order:add_to_cart' product.id %}" method="post">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between flex-lg-wrap">
                        <p class="text-dark fs-5 fw-bold">${{ product.price }}</p>
                        <button type="submit" class="btn border border-secondary rounded-pill px-3 py-1 mb-4 text-primary">
                            <i class="fa fa-shopping-bag me-2 text-primary"></i>{% trans "Add to cart" %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    {% endfor %}
</div>

templates/partials/search.html
{% load i18n %}

<form method="get" action="{% url 'store:search' %}">
    {% if style == 'button' %}
        <div class="position-relative mx-auto">
            <input 
                class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill" 
                name="searched" 
                type="text" 
                placeholder="{% trans 'Search for tea...' %}"
                value="{{ search_query }}">
            <button 
                type="submit" 
                class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-100" 
                style="top: 0; right: 25%;">{% trans "Search Now" %}</button>
        </div>
    {% else %}
        <div class="input-group mx-auto d-flex {{ extra_classes|default:'' }}">            
            <input 
                type="text" 
                name="searched" 
                class="form-control p-3" 
                placeholder="{% trans 'Search for tea...' %}"
                aria-describedby="search-icon-1"
                value="{{ search_query }}">
            <button id="search-icon-1" class="input-group-text p-3" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>
    {% endif %}
</form>

templates/partials/single-page-header.html
{% load i18n %}

<div class="container-fluid page-header py-5">
    <h1 class="text-center text-white display-6">{{ page_title }}</h1>
    <ol class="breadcrumb justify-content-center mb-0">
        <li class="breadcrumb-item"><a href="{% url 'store:home' %}">{% trans "Home" %}</a></li>
        <li class="breadcrumb-item active text-white"><a href="{% url 'store:shop' %}">{% trans "Shop" %}</a></li>
        {% if category %}
            <li class="breadcrumb-item active text-white"><a href="{% url 'store:category_page' category.slug %}">{{ category }}</a></li>
        {% endif %}    
    </ol>
</div>